/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DaoProduto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Produto;

/**
 *
 * @author Laboratorio
 */
public class FrmProduto extends javax.swing.JFrame {

    List<Produto> lista = new ArrayList<Produto>();
    DaoProduto dao;

    public FrmProduto() {
        initComponents();
        listarvalores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbProdu = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Código = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        txtIdprodu = new javax.swing.JTextField();
        txtNomeP = new javax.swing.JTextField();
        txtCate = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btSalvar2 = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btExluir = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdu = new javax.swing.JTable();
        btSair = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        lbProdu.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lbProdu.setText("PRODUTOS");

        lbId.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        lbId.setText("Id:");

        lbNome.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        lbNome.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        jLabel3.setText("Categoria:");

        Código.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        Código.setText("Código:");

        lbValor.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        lbValor.setText("Valor:");

        txtIdprodu.setEditable(false);

        btSalvar2.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btSalvar2.setText("Salvar");
        btSalvar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvar2ActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btExluir.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btExluir.setText("Excluir");
        btExluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExluirActionPerformed(evt);
            }
        });

        btAlterar.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        tbProdu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nome", "Categoria", "Código", "Valor"
            }
        ));
        tbProdu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProduMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProdu);

        btSair.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        txtBuscar.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        jLabel2.setText("Código");

        btBuscar.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        jLabel1.setText("Consultar por código do produto");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download-removebg-preview.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addComponent(lbProdu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(732, 732, 732)
                        .addComponent(btSair))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btLimpar)
                        .addGap(128, 128, 128)
                        .addComponent(btAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(btExluir)
                        .addGap(18, 18, 18)
                        .addComponent(btSalvar2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbId)
                                            .addComponent(lbNome))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtIdprodu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtNomeP)
                                    .addComponent(txtCate)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Código)
                                    .addComponent(lbValor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscar)))
                        .addGap(136, 136, 136))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProdu)
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbId)
                            .addComponent(txtIdprodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(txtNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Código))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar2)
                    .addComponent(btExluir)
                    .addComponent(btAlterar)
                    .addComponent(btLimpar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSair)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvar2ActionPerformed
        salvarProdu();
        limpar();
        listarvalores();
    }//GEN-LAST:event_btSalvar2ActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btExluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExluirActionPerformed
        excluirProdu();
        limpar();
        listarvalores();
    }//GEN-LAST:event_btExluirActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarProdu();
        limpar();
        listarvalores();
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        listarporcod();
    }//GEN-LAST:event_btBuscarActionPerformed

    private void tbProduMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProduMouseClicked
        carregar();
    }//GEN-LAST:event_tbProduMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Código;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btSalvar1;
    private javax.swing.JButton btSalvar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbProdu;
    private javax.swing.JLabel lbValor;
    private javax.swing.JTable tbProdu;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCate;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtIdprodu;
    private javax.swing.JTextField txtNomeP;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void salvarProdu() {
        try {
            Produto produ = new Produto();
            produ.setNome_produ(txtNomeP.getText());
            produ.setCategoria(txtCate.getText());
            produ.setCod_produ(Integer.parseInt(txtCod.getText()));
            produ.setValor(Float.parseFloat(txtValor.getText()));

            dao = new DaoProduto();
            dao.salvarProduto(produ);
            JOptionPane.showMessageDialog(null, "Inserido com sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Impossível salvar preecha os campos corretamente" + e.toString());
        }

    }

    private void excluirProdu() {
        try {
            Produto produ = new Produto();
            produ.setId_produ(Integer.parseInt(txtIdprodu.getText()));

            dao = new DaoProduto();
            dao.excluirProduto(produ);
            JOptionPane.showMessageDialog(null, "Excluído com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao excluir os dados." + e.toString());
        }

    }

    private void alterarProdu() {
        try {
            Produto produ = new Produto();
            produ.setId_produ(Integer.parseInt(txtIdprodu.getText()));
            produ.setNome_produ(txtNomeP.getText());
            produ.setCategoria(txtCate.getText());
            produ.setCod_produ(Integer.parseInt(txtCod.getText()));
            produ.setValor(Float.parseFloat(txtValor.getText()));

            dao = new DaoProduto();
            dao.alterarProduto(produ);
            JOptionPane.showMessageDialog(null, "Alterado sucesso");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Impossível alterar preecha os campos corretamente" + e.toString());
        }
    }

    private void limpar() {
        txtIdprodu.setText("");
        txtNomeP.setText("");
        txtCate.setText("");
        txtCod.setText("");
        txtValor.setText("");
        txtBuscar.setText("");
    }

    private void listarvalores() {
        try {
            DaoProduto produ = new DaoProduto();
            List<Produto> lista = produ.getProdutos();
            DefaultTableModel model = (DefaultTableModel) tbProdu.getModel();
            model.setNumRows(0);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_produ(),
                    lista.get(num).getNome_produ(),
                    lista.get(num).getCategoria(),
                    lista.get(num).getCod_produ(),
                    lista.get(num).getValor(),});
            }
            tbProdu.revalidate();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
        }
    }

    private void listarporcod() {
        try {
            int cod = (Integer.parseInt(txtBuscar.getText()));
            DaoProduto produ = new DaoProduto();
            List<Produto> lista = produ.PesquisarPorCodProdu(cod);
            DefaultTableModel model = (DefaultTableModel) tbProdu.getModel();
            model.setNumRows(0);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_produ(),
                    lista.get(num).getNome_produ(),
                    lista.get(num).getCategoria(),
                    lista.get(num).getCod_produ(),
                    lista.get(num).getValor(),});
            }
            tbProdu.revalidate();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Valores: " + erro);
        }
    }

    private void carregar() {
        txtIdprodu.setText(tbProdu.getValueAt(tbProdu.getSelectedRow(), 0).toString());
        txtNomeP.setText(tbProdu.getValueAt(tbProdu.getSelectedRow(), 1).toString());
        txtCate.setText(tbProdu.getValueAt(tbProdu.getSelectedRow(), 2).toString());
        txtCod.setText(tbProdu.getValueAt(tbProdu.getSelectedRow(), 3).toString());
        txtValor.setText(tbProdu.getValueAt(tbProdu.getSelectedRow(), 4).toString());
    }
}
